
---------------------------------------------------------
--  This code is generated by Terasic System Builder
--  
--  Group 4 has 3 members:
--    Le Thanh Hai       1851027
--    Nguyen Hoang Tuan  1851018
--    Dang Vu Kim Ky     1812744
---------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity Four_FFT is
port
(

	------------ CLOCK ------------
	clk        	:in    	std_logic;
	data            	:in    	std_logic_vector(7 downto 0);
	addr   		:in    	std_logic_vector(4 downto 0);
	Wr_en,CS,rst		:in    	std_logic;
	--Re1,Im1, Re2, Im2, Re3, Im3, Re4,Im4            :buffer  std_logic_vector(7 downto 0);
	dataout: out std_logic_vector(7 downto 0);
   done              :out    	std_logic

	------------ SW ------------
	--SW              	:in    	std_logic_vector(9 downto 0);

	------------ LED ------------
	--LEDR            	:out   	std_logic_vector(9 downto 0)
);

end entity;

---------------------------------------------------------
--  Structural coding
---------------------------------------------------------

architecture rtl of Four_FFT is

signal w_in1, w_Re1, w_Im1, w_Re2, w_Im2, w_Re3, w_Im3, w_Re4, w_Im4 : std_logic_vector(7 downto 0);
component sort is
Port ( 
   clk        	: in  std_logic;
	WR,rst 		: in  std_logic;
	addr			: in    	std_logic_vector(4 downto 0);
	data        : in    	std_logic_vector(7 downto 0);
	start       : buffer std_logic;
	Re1,Im1, Re2, Im2, Re3, Im3, Re4,Im4            :buffer  std_logic_vector(7 downto 0)
	);
end component;


component core_fourFFT is
Port (
   clk,start      : in std_logic;
    Re1, Im1, Re2, Im2, Re3, Im3, Re4, Im4 :in    	std_logic_vector(7 downto 0);
	 done : buffer std_logic;
	 addr_r: in std_logic_vector(4 downto 0);
	 dataout: out    	std_logic_vector(7 downto 0)
	 --outRe1, outIm1, outRe2, outIm2 : buffer STD_LOGIC_VECTOR(7 DOWNTO 0);
	 --outRe3, outIm3, outRe4, outIm4 : buffer STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
end component;


signal start  		  : std_logic;

begin

-- body --

SORTING1: sort port map (clk,Wr_en and CS,rst,addr,data,start,w_Re1, w_Im1, w_Re2, w_Im2, w_Re3, w_Im3, w_Re4, w_Im4);
FFT:  core_fourFFT port map (clk,start,w_Re1, w_Im1, w_Re2, w_Im2, w_Re3, w_Im3, w_Re4, w_Im4,done,addr,dataout);
end rtl;

